# -*- coding: utf-8 -*-
"""Customer Segmentation Business.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-oFnVdTu5o-oTdhVRqOjQCLDOc9JQ8YV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

df = pd.read_csv("Customers.csv")

X = df[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']]

scaler = StandardScaler()
x_scaled = scaler.fit_transform(X)

wcss = []
for i in range(1,11):
  kmeans = KMeans(n_clusters = i , random_state = 42)
  kmeans.fit(x_scaled)
  wcss.append(kmeans.inertia_)

plt.plot(range(1,11),wcss, marker = 'o')
plt.title('Elbow Method')
plt.xlabel('Number of cluster')
plt.ylabel('WCSS')
plt.grid(True)
plt.show()

kmeans = KMeans(n_clusters= 4, random_state = 42)
y_kmeans = kmeans.fit_predict(x_scaled)
df['Cluster'] = y_kmeans

pca = PCA(n_components= 2)
components = pca.fit_transform(x_scaled)
plt.figure(figsize=(8, 6))
plt.scatter(components[:, 0], components[:, 1], c=y_kmeans, cmap='viridis', s=50)
plt.title('Customer Segments by PCA')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(x='Age', y='Spending Score (1-100)', hue='Cluster', data=df, palette='Set1')
plt.title('Customer Segments (Age vs Spending Score)')
plt.grid(True)
plt.show()

summary = df.groupby('Cluster')[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']].mean()
print(summary)